# apiVersion: v1
# kind: Service
# metadata:
#   label:
#     app: myapp
#   name: myapp-deployment
# spec:
#   selector:
#     app: mypp
#     type: ClusterIP
#   ports:
#   - protocol: TCP
#     port: 4444
#     targetPort: 4444
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-deployment
spec:
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
  selector:
    app: myapp
  type: ClusterIP
