apiVersion: v1
kind: Service
metadata:
  label:
    app: myapp
  name: myapp-deployment
spec:
  selector:
    app: mypp
    type: ClusterIP
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444
